### ISSUE TITLE
Wow, awesome work!

### ISSUE THREAD

**Issue by fullmetal-fred** [burggraf/postgrest-request-processing#1]
@burggraf I hope the rest of the Supabase team has seen this. This is the best architecture for RBAC I've seen yet on Supabase. 

I have a few tweaks I'm going to test out on this. This is because I have a more complex multi-tenant use-case. 
- Users can be assigned one role per tenant. 
- Roles are custom per tenant...they have a tenant_id column and boolean columns for CRUD permissions on each table / entity pretty much.
- Thus, I'll have the db_pre_request function jsonb serialize each of the roles for the given user into the claims as an array of objects.
- RLS policies will check the row in question to see if there is a role matching the row's tenant_id, and if that row allows select, insert, update, delete. 

Because of the work you've done here this has become WAY more efficient and scalable. I'll try to follow-up with the result when I get there. 

Cheers!

**Comment by burggraf** [comment]
Aweome, @chaoticgoodly!  Feel free to add to this repo with anything you want to add or anything you find interesting.

**Comment by bangdragon** [comment]
@chaoticgoodly could you post the code for me to learn. Thanks

**Comment by fullmetal-fred** [comment]
Hey @bangdragon I've issued a PR to merge my example into this repo. Stand by and watch #2. The README isn't done, but the code is there.

**Comment by bangdragon** [comment]
> Hey @bangdragon I've issued a PR to merge my example into this repo. Stand by and watch #2. The README isn't done, but the code is there.

Could you add these features:
- User can create multiple tenants like restaurants
- User who create restaurant can specify other user as role like manager, order operator.
- Other user can request to be a role.
- Manager of a restaurant can specify someone or accept request from someone, to be a role. And can remove role too.
Thanks

**Comment by fullmetal-fred** [comment]
Hi @bangdragon what you're asking for goes beyond the scope of what I'm sharing at this time...application logic isn't included. However I think you could accomplish everything you want here by customizing the RBAC and RLS policies I've given here as a starter...the bones are here but you're going to have to do the work to sort out how it should function.
