### ISSUE TITLE
Combining supabase-custom-claims with prp for performance and fresh data??

### ISSUE THREAD

**Issue by abdirahmn1** [burggraf/postgrest-request-processing#3]
If i understand correctly, am i able to use the [supabase-custom-claims](https://github.com/supabase-community/supabase-custom-claims) library in combination with `db_pre_request` in order to have my RLS rules evaluate and check against fresh data that was initialized by `db_pre_request`?

given this [`get_my_claim()`](https://github.com/supabase-community/supabase-custom-claims/blob/254e656bf8b77e6f09131cf1de6440b26c99f39e/install.sql#L38C23-L38C23)` function in the [supabase-custom-claims](https://github.com/supabase-community/supabase-custom-claims)

```sql
CREATE OR REPLACE FUNCTION get_my_claim(claim TEXT) RETURNS "jsonb"
    LANGUAGE "sql" STABLE
    AS $$
  select 
  	coalesce(nullif(current_setting('request.jwt.claims', true), '')::jsonb -> 'app_metadata' -> claim, null)
$$;
```

It retrieves from `request.jwt.claims` that was set by the `db_pre_request()` and since requests in postgres run in a transaction, `get_my_claim()` will be able to get the latest "fresh" data that was initialized by the `db_pre_request()` function? 

Is this true?? or am i missing something?

**Comment by burggraf** [comment]
> It retrieves from request.jwt.claims that was set by the db_pre_request() and since requests in postgres run in a transaction, get_my_claim() will be able to get the latest "fresh" data that was initialized by the db_pre_request() function?

Yes -- this will work!
